# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

# Seed LLM Models
llm_models = [
  {
    name: "GPT-4o",
    slug: "gpt-4o",
    description: "OpenAI's most advanced multimodal model, capable of processing text, images, and audio inputs.",
    url: "https://openai.com/index/hello-gpt-4o/",
    provider: "OpenAI",
    parameters: "Undisclosed",
    context_window: 128_000,
    license: "Proprietary",
    open_source: false,
    api_available: true,
    release_date: "2024-05-13"
  },
  {
    name: "GPT-4 Turbo",
    slug: "gpt-4-turbo",
    description: "An improved version of GPT-4 with better instruction following, JSON mode, and a 128K context window.",
    url: "https://openai.com/index/gpt-4/",
    provider: "OpenAI",
    parameters: "Undisclosed",
    context_window: 128_000,
    license: "Proprietary",
    open_source: false,
    api_available: true,
    release_date: "2024-04-09"
  },
  {
    name: "GPT-4",
    slug: "gpt-4",
    description: "OpenAI's large multimodal model that accepts text and image inputs and produces text outputs.",
    url: "https://openai.com/index/gpt-4/",
    provider: "OpenAI",
    parameters: "Undisclosed",
    context_window: 8_192,
    license: "Proprietary",
    open_source: false,
    api_available: true,
    release_date: "2023-03-14"
  },
  {
    name: "GPT-3.5 Turbo",
    slug: "gpt-3-5-turbo",
    description: "A fast, inexpensive model for simple tasks such as chat and text generation.",
    url: "https://openai.com/",
    provider: "OpenAI",
    parameters: "Undisclosed",
    context_window: 16_385,
    license: "Proprietary",
    open_source: false,
    api_available: true,
    release_date: "2022-11-30"
  },
  {
    name: "o1",
    slug: "o1",
    description: "OpenAI's reasoning model designed to solve hard problems across math, coding, and science.",
    url: "https://openai.com/index/introducing-openai-o1-preview/",
    provider: "OpenAI",
    parameters: "Undisclosed",
    context_window: 200_000,
    license: "Proprietary",
    open_source: false,
    api_available: true,
    release_date: "2024-12-17"
  },
  {
    name: "o3-mini",
    slug: "o3-mini",
    description: "A smaller, cost-efficient reasoning model from OpenAI optimized for STEM tasks.",
    url: "https://openai.com/",
    provider: "OpenAI",
    parameters: "Undisclosed",
    context_window: 200_000,
    license: "Proprietary",
    open_source: false,
    api_available: true,
    release_date: "2025-01-31"
  },
  {
    name: "Claude 3.5 Sonnet",
    slug: "claude-3-5-sonnet",
    description: "Anthropic's most intelligent model, excelling at complex analysis, coding, and creative tasks.",
    url: "https://www.anthropic.com/claude/sonnet",
    provider: "Anthropic",
    parameters: "Undisclosed",
    context_window: 200_000,
    license: "Proprietary",
    open_source: false,
    api_available: true,
    release_date: "2024-10-22"
  },
  {
    name: "Claude 3.5 Haiku",
    slug: "claude-3-5-haiku",
    description: "Anthropic's fastest model, optimized for speed and cost-efficiency.",
    url: "https://www.anthropic.com/claude/haiku",
    provider: "Anthropic",
    parameters: "Undisclosed",
    context_window: 200_000,
    license: "Proprietary",
    open_source: false,
    api_available: true,
    release_date: "2024-11-04"
  },
  {
    name: "Claude 3 Opus",
    slug: "claude-3-opus",
    description: "Anthropic's most powerful model for highly complex tasks requiring deep analysis.",
    url: "https://www.anthropic.com/claude",
    provider: "Anthropic",
    parameters: "Undisclosed",
    context_window: 200_000,
    license: "Proprietary",
    open_source: false,
    api_available: true,
    release_date: "2024-03-04"
  },
  {
    name: "Gemini 2.0 Flash",
    slug: "gemini-2-0-flash",
    description: "Google's fast and versatile multimodal model with native tool use and agentic capabilities.",
    url: "https://deepmind.google/technologies/gemini/flash/",
    provider: "Google",
    parameters: "Undisclosed",
    context_window: 1_000_000,
    license: "Proprietary",
    open_source: false,
    api_available: true,
    release_date: "2025-02-25"
  },
  {
    name: "Gemini 1.5 Pro",
    slug: "gemini-1-5-pro",
    description: "Google's advanced multimodal model with a massive context window for complex reasoning tasks.",
    url: "https://deepmind.google/technologies/gemini/",
    provider: "Google",
    parameters: "Undisclosed",
    context_window: 2_000_000,
    license: "Proprietary",
    open_source: false,
    api_available: true,
    release_date: "2024-02-15"
  },
  {
    name: "Gemini 1.5 Flash",
    slug: "gemini-1-5-flash",
    description: "Google's lightweight multimodal model optimized for speed and efficiency.",
    url: "https://deepmind.google/technologies/gemini/flash/",
    provider: "Google",
    parameters: "Undisclosed",
    context_window: 1_000_000,
    license: "Proprietary",
    open_source: false,
    api_available: true,
    release_date: "2024-05-24"
  },
  {
    name: "Gemma 2",
    slug: "gemma-2",
    description: "Google's open-weight model family available in 2B, 9B, and 27B sizes.",
    url: "https://ai.google.dev/gemma",
    provider: "Google",
    parameters: "27B",
    context_window: 8_192,
    license: "Gemma License",
    open_source: true,
    api_available: true,
    github_url: "https://github.com/google-deepmind/gemma",
    release_date: "2024-06-27"
  },
  {
    name: "Llama 3.1 405B",
    slug: "llama-3-1-405b",
    description: "Meta's largest open-weight model with 405 billion parameters, competitive with top proprietary models.",
    url: "https://llama.meta.com/",
    provider: "Meta",
    parameters: "405B",
    context_window: 128_000,
    license: "Llama 3.1 Community License",
    open_source: true,
    api_available: true,
    github_url: "https://github.com/meta-llama/llama-models",
    release_date: "2024-07-23"
  },
  {
    name: "Llama 3.1 70B",
    slug: "llama-3-1-70b",
    description: "Meta's 70B parameter open-weight model for a wide range of language tasks.",
    url: "https://llama.meta.com/",
    provider: "Meta",
    parameters: "70B",
    context_window: 128_000,
    license: "Llama 3.1 Community License",
    open_source: true,
    api_available: true,
    github_url: "https://github.com/meta-llama/llama-models",
    release_date: "2024-07-23"
  },
  {
    name: "Llama 3.1 8B",
    slug: "llama-3-1-8b",
    description: "Meta's compact 8B parameter open-weight model efficient enough to run on a single GPU.",
    url: "https://llama.meta.com/",
    provider: "Meta",
    parameters: "8B",
    context_window: 128_000,
    license: "Llama 3.1 Community License",
    open_source: true,
    api_available: true,
    github_url: "https://github.com/meta-llama/llama-models",
    release_date: "2024-07-23"
  },
  {
    name: "Llama 3.3 70B",
    slug: "llama-3-3-70b",
    description: "Meta's latest 70B parameter model offering performance comparable to the 405B model.",
    url: "https://llama.meta.com/",
    provider: "Meta",
    parameters: "70B",
    context_window: 128_000,
    license: "Llama 3.3 Community License",
    open_source: true,
    api_available: true,
    github_url: "https://github.com/meta-llama/llama-models",
    release_date: "2024-12-06"
  },
  {
    name: "Mistral Large",
    slug: "mistral-large",
    description: "Mistral AI's flagship model for complex reasoning, multilingual tasks, and code generation.",
    url: "https://mistral.ai/",
    provider: "Mistral AI",
    parameters: "Undisclosed",
    context_window: 128_000,
    license: "Proprietary",
    open_source: false,
    api_available: true,
    release_date: "2024-11-18"
  },
  {
    name: "Mixtral 8x22B",
    slug: "mixtral-8x22b",
    description: "Mistral AI's open-weight mixture-of-experts model with strong performance across benchmarks.",
    url: "https://mistral.ai/news/mixtral-8x22b/",
    provider: "Mistral AI",
    parameters: "176B (MoE)",
    context_window: 65_536,
    license: "Apache 2.0",
    open_source: true,
    api_available: true,
    github_url: "https://github.com/mistralai/mistral-inference",
    release_date: "2024-04-17"
  },
  {
    name: "Mixtral 8x7B",
    slug: "mixtral-8x7b",
    description: "Mistral AI's sparse mixture-of-experts model that outperforms Llama 2 70B on most benchmarks.",
    url: "https://mistral.ai/news/mixtral-of-experts/",
    provider: "Mistral AI",
    parameters: "46.7B (MoE)",
    context_window: 32_768,
    license: "Apache 2.0",
    open_source: true,
    api_available: true,
    github_url: "https://github.com/mistralai/mistral-inference",
    release_date: "2023-12-11"
  },
  {
    name: "Mistral 7B",
    slug: "mistral-7b",
    description: "Mistral AI's first open-weight 7B model that outperforms Llama 2 13B on all benchmarks.",
    url: "https://mistral.ai/news/announcing-mistral-7b/",
    provider: "Mistral AI",
    parameters: "7B",
    context_window: 32_768,
    license: "Apache 2.0",
    open_source: true,
    api_available: true,
    github_url: "https://github.com/mistralai/mistral-inference",
    release_date: "2023-09-27"
  },
  {
    name: "DeepSeek-V3",
    slug: "deepseek-v3",
    description: "DeepSeek's powerful mixture-of-experts model with 671B total parameters.",
    url: "https://www.deepseek.com/",
    provider: "DeepSeek",
    parameters: "671B (MoE)",
    context_window: 128_000,
    license: "MIT",
    open_source: true,
    api_available: true,
    github_url: "https://github.com/deepseek-ai/DeepSeek-V3",
    release_date: "2024-12-26"
  },
  {
    name: "DeepSeek-R1",
    slug: "deepseek-r1",
    description: "DeepSeek's reasoning model that matches OpenAI o1 performance through reinforcement learning.",
    url: "https://www.deepseek.com/",
    provider: "DeepSeek",
    parameters: "671B (MoE)",
    context_window: 128_000,
    license: "MIT",
    open_source: true,
    api_available: true,
    github_url: "https://github.com/deepseek-ai/DeepSeek-R1",
    release_date: "2025-01-20"
  },
  {
    name: "DeepSeek-Coder-V2",
    slug: "deepseek-coder-v2",
    description: "DeepSeek's code-specialized model supporting 338 programming languages.",
    url: "https://www.deepseek.com/",
    provider: "DeepSeek",
    parameters: "236B (MoE)",
    context_window: 128_000,
    license: "MIT",
    open_source: true,
    api_available: true,
    github_url: "https://github.com/deepseek-ai/DeepSeek-Coder-V2",
    release_date: "2024-06-17"
  },
  {
    name: "Qwen2.5 72B",
    slug: "qwen2-5-72b",
    description: "Alibaba's flagship open-weight model with strong multilingual and coding capabilities.",
    url: "https://qwenlm.github.io/",
    provider: "Alibaba",
    parameters: "72B",
    context_window: 131_072,
    license: "Apache 2.0",
    open_source: true,
    api_available: true,
    github_url: "https://github.com/QwenLM/Qwen2.5",
    release_date: "2024-09-19"
  },
  {
    name: "Qwen2.5-Coder 32B",
    slug: "qwen2-5-coder-32b",
    description: "Alibaba's code-specialized model that rivals GPT-4o in coding tasks.",
    url: "https://qwenlm.github.io/",
    provider: "Alibaba",
    parameters: "32B",
    context_window: 131_072,
    license: "Apache 2.0",
    open_source: true,
    api_available: true,
    github_url: "https://github.com/QwenLM/Qwen2.5-Coder",
    release_date: "2024-11-12"
  },
  {
    name: "Phi-4",
    slug: "phi-4",
    description: "Microsoft's compact 14B parameter model excelling at reasoning and STEM tasks.",
    url: "https://azure.microsoft.com/en-us/products/phi",
    provider: "Microsoft",
    parameters: "14B",
    context_window: 16_384,
    license: "MIT",
    open_source: true,
    api_available: true,
    github_url: "https://github.com/microsoft/phi-4",
    release_date: "2024-12-12"
  },
  {
    name: "Phi-3 Medium",
    slug: "phi-3-medium",
    description: "Microsoft's 14B parameter small language model optimized for constrained environments.",
    url: "https://azure.microsoft.com/en-us/products/phi",
    provider: "Microsoft",
    parameters: "14B",
    context_window: 128_000,
    license: "MIT",
    open_source: true,
    api_available: true,
    github_url: "https://github.com/microsoft/Phi-3CookBook",
    release_date: "2024-05-21"
  },
  {
    name: "Phi-3 Mini",
    slug: "phi-3-mini",
    description: "Microsoft's 3.8B parameter small language model that can run on mobile devices.",
    url: "https://azure.microsoft.com/en-us/products/phi",
    provider: "Microsoft",
    parameters: "3.8B",
    context_window: 128_000,
    license: "MIT",
    open_source: true,
    api_available: true,
    github_url: "https://github.com/microsoft/Phi-3CookBook",
    release_date: "2024-04-23"
  },
  {
    name: "Command R+",
    slug: "command-r-plus",
    description: "Cohere's scalable model optimized for RAG and tool use in enterprise applications.",
    url: "https://cohere.com/command",
    provider: "Cohere",
    parameters: "104B",
    context_window: 128_000,
    license: "CC-BY-NC",
    open_source: true,
    api_available: true,
    release_date: "2024-04-04"
  },
  {
    name: "Command R",
    slug: "command-r",
    description: "Cohere's efficient model designed for RAG, tool use, and long context tasks.",
    url: "https://cohere.com/command",
    provider: "Cohere",
    parameters: "35B",
    context_window: 128_000,
    license: "CC-BY-NC",
    open_source: true,
    api_available: true,
    release_date: "2024-03-11"
  },
  {
    name: "DBRX",
    slug: "dbrx",
    description: "Databricks' open-source mixture-of-experts model for general-purpose language understanding.",
    url: "https://www.databricks.com/blog/introducing-dbrx-new-state-art-open-llm",
    provider: "Databricks",
    parameters: "132B (MoE)",
    context_window: 32_768,
    license: "Databricks Open Model License",
    open_source: true,
    api_available: true,
    github_url: "https://github.com/databricks/dbrx",
    release_date: "2024-03-27"
  },
  {
    name: "Yi-Large",
    slug: "yi-large",
    description: "01.AI's flagship large language model with strong multilingual capabilities.",
    url: "https://www.01.ai/",
    provider: "01.AI",
    parameters: "Undisclosed",
    context_window: 32_768,
    license: "Proprietary",
    open_source: false,
    api_available: true,
    release_date: "2024-05-13"
  },
  {
    name: "Yi-1.5 34B",
    slug: "yi-1-5-34b",
    description: "01.AI's open-weight 34B model with improved coding and reasoning capabilities.",
    url: "https://www.01.ai/",
    provider: "01.AI",
    parameters: "34B",
    context_window: 16_384,
    license: "Apache 2.0",
    open_source: true,
    api_available: true,
    github_url: "https://github.com/01-ai/Yi",
    release_date: "2024-05-13"
  },
  {
    name: "Falcon 180B",
    slug: "falcon-180b",
    description: "TII's 180 billion parameter model, one of the largest openly available language models.",
    url: "https://falconllm.tii.ae/",
    provider: "TII",
    parameters: "180B",
    context_window: 2_048,
    license: "Falcon-180B TII License",
    open_source: true,
    api_available: false,
    release_date: "2023-09-06"
  },
  {
    name: "Falcon 40B",
    slug: "falcon-40b",
    description: "TII's 40 billion parameter open-source causal language model.",
    url: "https://falconllm.tii.ae/",
    provider: "TII",
    parameters: "40B",
    context_window: 2_048,
    license: "Apache 2.0",
    open_source: true,
    api_available: false,
    release_date: "2023-05-25"
  },
  {
    name: "Grok-2",
    slug: "grok-2",
    description: "xAI's frontier language model with advanced reasoning and coding capabilities.",
    url: "https://x.ai/",
    provider: "xAI",
    parameters: "Undisclosed",
    context_window: 131_072,
    license: "Proprietary",
    open_source: false,
    api_available: true,
    release_date: "2024-08-13"
  },
  {
    name: "Grok-1",
    slug: "grok-1",
    description: "xAI's open-weight 314B parameter mixture-of-experts model.",
    url: "https://x.ai/",
    provider: "xAI",
    parameters: "314B (MoE)",
    context_window: 8_192,
    license: "Apache 2.0",
    open_source: true,
    api_available: false,
    github_url: "https://github.com/xai-org/grok-1",
    release_date: "2024-03-17"
  },
  {
    name: "Jamba 1.5 Large",
    slug: "jamba-1-5-large",
    description: "AI21 Labs' hybrid SSM-Transformer model with a 256K context window.",
    url: "https://www.ai21.com/jamba",
    provider: "AI21 Labs",
    parameters: "398B (MoE)",
    context_window: 256_000,
    license: "Jamba Open Model License",
    open_source: true,
    api_available: true,
    release_date: "2024-08-22"
  },
  {
    name: "StableLM 2 12B",
    slug: "stablelm-2-12b",
    description: "Stability AI's 12B parameter language model trained on multilingual data.",
    url: "https://stability.ai/",
    provider: "Stability AI",
    parameters: "12B",
    context_window: 4_096,
    license: "Stability AI Community License",
    open_source: true,
    api_available: false,
    github_url: "https://github.com/Stability-AI/StableLM",
    release_date: "2024-02-07"
  },
  {
    name: "OLMo 2 13B",
    slug: "olmo-2-13b",
    description: "AI2's fully open language model with open training data, code, and weights.",
    url: "https://allenai.org/olmo",
    provider: "Allen Institute for AI",
    parameters: "13B",
    context_window: 4_096,
    license: "Apache 2.0",
    open_source: true,
    api_available: false,
    github_url: "https://github.com/allenai/OLMo",
    release_date: "2024-11-01"
  },
  {
    name: "InternLM2.5 20B",
    slug: "internlm2-5-20b",
    description: "Shanghai AI Lab's open-source model with strong reasoning and long-context capabilities.",
    url: "https://internlm.intern-ai.org.cn/",
    provider: "Shanghai AI Lab",
    parameters: "20B",
    context_window: 1_000_000,
    license: "Apache 2.0",
    open_source: true,
    api_available: true,
    github_url: "https://github.com/InternLM/InternLM",
    release_date: "2024-07-03"
  },
  {
    name: "Nemotron-4 340B",
    slug: "nemotron-4-340b",
    description: "NVIDIA's large language model family optimized for generating synthetic training data.",
    url: "https://www.nvidia.com/en-us/ai-data-science/generative-ai/",
    provider: "NVIDIA",
    parameters: "340B",
    context_window: 4_096,
    license: "NVIDIA Open Model License",
    open_source: true,
    api_available: true,
    release_date: "2024-06-14"
  },
  {
    name: "Arctic",
    slug: "arctic",
    description: "Snowflake's enterprise-grade open-source MoE model optimized for SQL and coding.",
    url: "https://www.snowflake.com/en/data-cloud/arctic/",
    provider: "Snowflake",
    parameters: "480B (MoE)",
    context_window: 4_096,
    license: "Apache 2.0",
    open_source: true,
    api_available: false,
    github_url: "https://github.com/Snowflake-Labs/snowflake-arctic",
    release_date: "2024-04-24"
  },
  {
    name: "CodeLlama 70B",
    slug: "codellama-70b",
    description: "Meta's code-specialized model built on Llama 2, supporting many programming languages.",
    url: "https://ai.meta.com/blog/code-llama-large-language-model-coding/",
    provider: "Meta",
    parameters: "70B",
    context_window: 16_384,
    license: "Llama 2 Community License",
    open_source: true,
    api_available: true,
    github_url: "https://github.com/meta-llama/codellama",
    release_date: "2024-01-29"
  },
  {
    name: "StarCoder2 15B",
    slug: "starcoder2-15b",
    description: "BigCode's open-source code model trained on The Stack v2 dataset.",
    url: "https://huggingface.co/bigcode/starcoder2-15b",
    provider: "BigCode",
    parameters: "15B",
    context_window: 16_384,
    license: "BigCode Open RAIL-M",
    open_source: true,
    api_available: false,
    github_url: "https://github.com/bigcode-project/starcoder2",
    release_date: "2024-02-28"
  },
  {
    name: "WizardLM-2 8x22B",
    slug: "wizardlm-2-8x22b",
    description: "Microsoft's instruction-tuned MoE model with strong performance on complex tasks.",
    url: "https://wizardlm.github.io/WizardLM2/",
    provider: "Microsoft",
    parameters: "176B (MoE)",
    context_window: 65_536,
    license: "Apache 2.0",
    open_source: true,
    api_available: false,
    github_url: "https://github.com/nlpxucan/WizardLM",
    release_date: "2024-04-15"
  },
  {
    name: "Cohere Embed v3",
    slug: "cohere-embed-v3",
    description: "Cohere's state-of-the-art embedding model for search and retrieval.",
    url: "https://cohere.com/embed",
    provider: "Cohere",
    parameters: "Undisclosed",
    context_window: 512,
    license: "Proprietary",
    open_source: false,
    api_available: true,
    release_date: "2023-11-02"
  },
  {
    name: "Claude 2.1",
    slug: "claude-2-1",
    description: "An earlier Anthropic model with 200K context window and reduced hallucination rates.",
    url: "https://www.anthropic.com/",
    provider: "Anthropic",
    parameters: "Undisclosed",
    context_window: 200_000,
    license: "Proprietary",
    open_source: false,
    api_available: true,
    release_date: "2023-11-21"
  },
  {
    name: "PaLM 2",
    slug: "palm-2",
    description: "Google's next-generation language model with improved multilingual and reasoning capabilities.",
    url: "https://ai.google/discover/palm2",
    provider: "Google",
    parameters: "Undisclosed",
    context_window: 32_768,
    license: "Proprietary",
    open_source: false,
    api_available: true,
    paper_url: "https://arxiv.org/abs/2305.10403",
    release_date: "2023-05-10"
  },
  {
    name: "Llama 2 70B",
    slug: "llama-2-70b",
    description: "Meta's second-generation open-weight model available for research and commercial use.",
    url: "https://llama.meta.com/",
    provider: "Meta",
    parameters: "70B",
    context_window: 4_096,
    license: "Llama 2 Community License",
    open_source: true,
    api_available: true,
    github_url: "https://github.com/meta-llama/llama",
    paper_url: "https://arxiv.org/abs/2307.09288",
    release_date: "2023-07-18"
  },
]

llm_models.each do |attrs|
  LlmModel.find_or_create_by(slug: attrs[:slug]) do |model|
    model.assign_attributes(attrs)
  end
end

puts "Seeded #{LlmModel.count} LLM models"
